### ISSUE TITLE
Null Response causing all players to get kicked.

### ISSUE THREAD

**Issue by levahmc** [track/plugin#19]
Hey,

I am experiencing a issue where the plugin will randomly spam a bunch of the same exception and then kick everyone. This happens every single day at a random interval.

> [11:40:53] [Craft Scheduler Thread - 5921 - Analyse/WARN]: [Analyse] Plugin Analyse v1.1.12 generated an exception while executing task 28571744
java.lang.NullPointerException: Cannot invoke "net.analyse.plugin.bukkit.libs.okhttp3.Response.code()" because "response" is null
	at net.analyse.sdk.AnalyseSDK.getLocationFromIP(AnalyseSDK.java:201) ~[bukkit-analyse-1.1.12.jar:?]
	at net.analyse.sdk.AnalyseSDK.sendPlayerSession(AnalyseSDK.java:241) ~[bukkit-analyse-1.1.12.jar:?]
	at net.analyse.plugin.bukkit.AnalysePlugin.sendData(AnalysePlugin.java:229) ~[bukkit-analyse-1.1.12.jar:?]
	at net.analyse.plugin.bukkit.AnalysePlugin.lambda$sendPlayerSessionInformation$3(AnalysePlugin.java:174) ~[bukkit-analyse-1.1.12.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[pufferfish-1.19.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[11:40:53] [Craft Scheduler Thread - 5894 - Analyse/WARN]: 	at bukkit-analyse-1.1.12.jar//net.analyse.plugin.bukkit.libs.okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
[11:40:53] [Craft Scheduler Thread - 5894 - Analyse/WARN]: 	at bukkit-analyse-1.1.12.jar//net.analyse.plugin.bukkit.libs.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
[11:40:53] [Craft Scheduler Thread - 5894 - Analyse/WARN]: 	at bukkit-analyse-1.1.12.jar//net.analyse.plugin.bukkit.libs.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[11:40:53] [Craft Scheduler Thread - 5894 - Analyse/WARN]: 	at bukkit-analyse-1.1.12.jar//net.analyse.plugin.bukkit.libs.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
[11:40:53] [Craft Scheduler Thread - 5894 - Analyse/WARN]: 	at bukkit-analyse-1.1.12.jar//net.analyse.plugin.bukkit.libs.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[11:40:53] [Craft Scheduler Thread - 5894 - Analyse/WARN]: 	at bukkit-analyse-1.1.12.jar//net.analyse.plugin.bukkit.libs.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
[11:40:53] [Craft Scheduler Thread - 5894 - Analyse/WARN]: 	at bukkit-analyse-1.1.12.jar//net.analyse.plugin.bukkit.libs.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[11:40:53] [Craft Scheduler Thread - 5894 - Analyse/WARN]: 	at bukkit-analyse-1.1.12.jar//net.analyse.plugin.bukkit.libs.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
[11:40:53] [Craft Scheduler Thread - 5894 - Analyse/WARN]: 	at bukkit-analyse-1.1.12.jar//net.analyse.plugin.bukkit.libs.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[11:40:53] [Craft Scheduler Thread - 5894 - Analyse/WARN]: 	at bukkit-analyse-1.1.12.jar//net.analyse.plugin.bukkit.libs.okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
[11:40:53] [Craft Scheduler Thread - 5894 - Analyse/WARN]: 	at bukkit-analyse-1.1.12.jar//net.analyse.plugin.bukkit.libs.okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
[11:40:53] [Craft Scheduler Thread - 5894 - Analyse/WARN]: 	at bukkit-analyse-1.1.12.jar//net.analyse.sdk.request.APIRequest.send(APIRequest.java:39)
[11:40:53] [Craft Scheduler Thread - 5894 - Analyse/WARN]: 	at bukkit-analyse-1.1.12.jar//net.analyse.sdk.AnalyseSDK.getLocationFromIP(AnalyseSDK.java:199)
[11:40:53] [Craft Scheduler Thread - 5894 - Analyse/WARN]: 	at bukkit-analyse-1.1.12.jar//net.analyse.sdk.AnalyseSDK.sendPlayerSession(AnalyseSDK.java:241)
[11:40:53] [Craft Scheduler Thread - 5894 - Analyse/WARN]: 	at bukkit-analyse-1.1.12.jar//net.analyse.plugin.bukkit.AnalysePlugin.sendData(AnalysePlugin.java:229)
[11:40:53] [Craft Scheduler Thread - 5894 - Analyse/WARN]: 	at bukkit-analyse-1.1.12.jar//net.analyse.plugin.bukkit.AnalysePlugin.lambda$sendPlayerSessionInformation$3(AnalysePlugin.java:174)
[11:40:53] [Craft Scheduler Thread - 5894 - Analyse/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[11:40:53] [Craft Scheduler Thread - 5894 - Analyse/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[11:40:53] [Craft Scheduler Thread - 5894 - Analyse/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[11:40:53] [Craft Scheduler Thread - 5894 - Analyse/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[11:40:53] [Craft Scheduler Thread - 5894 - Analyse/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[11:40:53] [Craft Scheduler Thread - 5894 - Analyse/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by heychazza** [comment]
Sorry that you faced this issue, it has now been resolved.

https://github.com/track/plugin/releases/tag/1.1.13
