### ISSUE TITLE
Plugin does not accept any commands

### ISSUE THREAD

**Issue by nathanielcutajar** [track/plugin#27]
I have recently updated the plugin from version 1 to version 2 as I previously could not use it since it required redis.
Whilst I am glad that the plugin now drops that requirement, I see a lot of issues with it, one of them being that I cannot even execute anything.

My first issue is that whilst I see that the plugin is active, if I do /analyse in the server or 'analyse' command on the console, both return that the command does not exist.

On top of that, I get this warning in the console:

```
24.05 10:02:30 [Server] WARN Error dispatching event PostLoginEvent(player=nathanieldbest) to listener net.analyse.plugin.event.PlayerJoinListener@7db2b614
24.05 10:02:30 [Server] INFO java.lang.NullPointerException: Cannot invoke "java.net.InetAddress.getHostAddress()" because the return value of "java.net.InetSocketAddress.getAddress()" is null
24.05 10:02:30 [Server] INFO at net.analyse.plugin.event.PlayerJoinListener.onPostLogin(PlayerJoinListener.java:22) ~[?:?]
24.05 10:02:30 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
24.05 10:02:30 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
24.05 10:02:30 [Server] INFO at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
24.05 10:02:30 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
24.05 10:02:30 [Server] INFO at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
24.05 10:02:30 [Server] INFO at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
24.05 10:02:30 [Server] INFO at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:467) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
24.05 10:02:30 [Server] INFO at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:635) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
24.05 10:02:30 [Server] INFO at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
24.05 10:02:30 [Server] INFO at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
24.05 10:02:30 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
24.05 10:02:30 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
24.05 10:02:30 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
24.05 10:02:30 [Server] INFO at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
24.05 10:02:30 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
``` 

Apart from that, the plugin no longer generates a config file or a folder for itself. Not sure if this is intentional or not.

I have updated waterfall, and the servers to 1.19.4, and running the latest version of the plugin (v2.0.3 as of writing)
I cannot use the plugin at all. What is happening please?

**Comment by heychazza** [comment]
Hi there,

Apologies for the issues you've been facing, a release (v2.0.4) has just gone out that should fix this. You are also correct that v2 on the proxy no longer generates a config file, this is because the configuration is handled on your Spigot server.

In addition, the proxy plugin doesn't have any commands and configuration is done on your Spigot side, please see our [Installation](https://analyse.net/docs/installation) documentation for more info on this.

Thanks for reporting the bug!
