### ISSUE TITLE
Rate Limit

### ISSUE THREAD

**Issue by bobhenl** [track/plugin#35]
Hi, what to do with this, please?
```
[11:07:00] [OkHttp https://analytics.tebex.io/.../WARN]: [Analyse] Failed to track player session: You are being rate limited.
[11:07:00] [OkHttp https://analytics.tebex.io/.../WARN]: io.tebex.analytics.sdk.request.exception.RateLimitException: You are being rate limited.
[11:07:00] [OkHttp https://analytics.tebex.io/.../WARN]: 	at bukkit-analyse-2.1.0.jar//io.tebex.analytics.sdk.SDK.lambda$trackPlayerSession$3(SDK.java:214)
[11:07:00] [OkHttp https://analytics.tebex.io/.../WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[11:07:00] [OkHttp https://analytics.tebex.io/.../WARN]: 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[11:07:00] [OkHttp https://analytics.tebex.io/.../WARN]: 	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
[11:07:00] [OkHttp https://analytics.tebex.io/.../WARN]: 	at bukkit-analyse-2.1.0.jar//io.tebex.analytics.sdk.request.AnalyseRequest$1.onResponse(AnalyseRequest.java:100)
[11:07:00] [OkHttp https://analytics.tebex.io/.../WARN]: 	at bukkit-analyse-2.1.0.jar//io.tebex.analytics.libs.okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:545)
[11:07:00] [OkHttp https://analytics.tebex.io/.../WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[11:07:00] [OkHttp https://analytics.tebex.io/.../WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[11:07:00] [OkHttp https://analytics.tebex.io/.../WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by heychazza** [comment]
Hey Bob,

Apologies for facing the rate limit issue, this should now be fixed but if it doesn't, feel free to submit another issue.
